### PR TITLE
Deck selection modal

### PR DESCRIPTION
**Pull request by porterga**
Deck selection modal comes up on game start and on reset. Does not do anything when english or spanish is selected, but this is hopefully a start.

### CODE REVIEW

**Comment by disalvoj** [comment]
I didn't know about the "git wont let me continue without commit" changes until now. For some reason git stash wasn't working and my only option that I knew of was git commit. Make sure someone reviews this portion of the code and make sure I didn't delete anything important. From what I can see I rewrote all of it in a different way.

**Comment by porterga** [comment]
So this looks really funky now, I will try to revert it to a previous commit and work on it from there.

**Comment by porterga** [comment]
Fixed the deletions, should be ready to merge. I would like someone to test it though, just in case.

**Comment by Manason** [comment]
Looks great. Love the look of the modal.

**Pull request merged**
