### PR TITLE
Css changes

### PR DESCRIPTION
**Pull request by disalvoj**
I've updated the CSS:
-formatted the buttons positions
-formatted the help screen
-removed the dashed border around the columns
-re-positioned the title, 1-4 buttons, and the columns of cards
Fixes issue #42

### CODE REVIEW

**Comment by porterga** [comment]
So when I compile and execute this branch, the CSS still looks kinda funky and the dashes around the columns are still there. This could be an issue with me running it, but would you try running it on your own machine again and make sure it looks as intended?

**Comment by disalvoj** [comment]
I just did a pull request and recompiled. everything seems to be working for me.

**Comment by loughrao** [comment]
Dashes are gone, looks pretty good however there is still seem to be some scaling issues. I think it is okay if we just leave it as because the game works best in a full screen window either way. If you have time maybe take a look at it with your browser at half width, going to merge this now though and we can work on the other issue if we have time.

**Comment by Manason** [comment]
issue #57 created to document existing issues with css

**Pull request merged**
